FROM node:9.10.1

MAINTAINER Julien Paris

ENV HOST 0.0.0.0

# create app folder in container
RUN echo "-->>> creating app folder" && \
  mkdir -p /app
WORKDIR /app

# copy packages and install
COPY package.json /app
RUN echo "-->>> installing packages" && \
  npm install

# copy rest of app folder
COPY . /app

# RUN npm run build 

# expose port on container
EXPOSE 3001

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3001

CMD ["npm", "run", "dev"]