export const BasicDictionnary = {

  // DEFAULT STRINGS
  empty_dict : {
    en : " ",
    es : " ",
    de : " ",
    tr : " ",
    fr : " ",
  },
  shuffle : {
    en : "randomly shuffle the data",
    es : "mezclar los datos",
    de : "shuffle the data",
    tr : "shuffle the data",
    fr : "mélanger aléatoirement les données",
  },

  // MAP VIEW
  map_layers : {
    en : "Layers",
    es : "Capas",
    de : "Layers",
    tr : "Layers",
    fr : "Calques",
  },

  // TABS VIEWS
  tab_map : {
    en : "map",
    es : "mapa",
    de : "Karte",
    tr : "harita",
    fr : "carte",
  },
  tab_table : {
    en : "table",
    es : "tabula",
    de : "Tabelle",
    tr : "tablo",
    fr : "table",
  },
  tab_list : {
    en : "list",
    es : "lista",
    de : "Liste",
    tr : "liste",
    fr : "liste",
  },
  tab_stat : {
    en : "stats",
    es : "datos",
    de : "statis",
    tr : "istat",
    fr : "données",
  },
  tab_calendar : {
    en : "calendar",
    es : "calendario",
    de : "calendar",
    tr : "calendar",
    fr : "calendrier",
  },
  tab_export : {
    en : "export data",
    es : "exportar los datos",
    de : "export",
    tr : "export",
    fr : "exporter les données",
  },

  // TABLE VIEW
  table_to_detail : {
    en : "detail",
    es : "detalle",
    de : "view",
    tr : "view",
    fr : "détail",
  },
  results_per_page : {
    en : "resuts per page",
    es : "resultados por pagina",
    de : "resuts per page",
    tr : "resuts per page",
    fr : "résultats par page",
  },
  results : {
    en : "resuts",
    es : "resultados",
    de : "resuts",
    tr : "resuts",
    fr : "résultats",
  },
  per_page : {
    en : "per page",
    es : "por pagina",
    de : "per page",
    tr : "per page",
    fr : "par page",
  },
  page : {
    en : "page",
    es : "pagina",
    de : "page",
    tr : "sayfa",
    fr : "page",
  },

  //
  request_loading : {
    en : "request is pending...",
    es : "búsqueda está pendiente...",
    de : "to do de",
    tr : "to do tr",
    fr : "Recherche en cours...",
  },
  no_results : {
    en : "No results",
    es : "No resultados",
    de : "to do de",
    tr : "to do tr",
    fr : "Pas de résultats",
  },
  no_results_help : {
    en : "For more results, please change your search criterias",
    es : "Para tener mas resultados, cambie sus criterios",
    de : "to do de",
    tr : "to do tr",
    fr : "Pour obtenir plus de résultats, modifiez vos critères de recherche",
  },
  delete_all_filters : {
    en : "Delete all filters",
    es : "Suprimir todos los fieltros",
    de : "to do de",
    tr : "to do tr",
    fr : "Supprimer tous les filtres",
  },

  // UUID NOT AUTHORIZED
  uuid_blocked : {
    en : "Sorry, this UUID exists but is blocked",
    es : "Lo sentamos, este UUID existe pero esta bloqueado",
    de : "to do de",
    tr : "to do tr",
    fr : "Désolé, cet UUID existe mais est bloqué",
  },
  contact_team : {
    en : "Please contact the Apiviz team or your admin sys",
    es : "Por favor contacte el Apiviz team o sea su adminn sys",
    de : "to do de",
    tr : "to do tr",
    fr : "Merci de contacter la team Apiviz ou votre administrateur système",
  },

  // ERRORS / RESPONSES BACKEND
  error_1a : {
    en : "Error during process",
    es : "Error durante el proceso",
    de : "to do de",
    tr : "to do tr",
    fr : "Erreur du process",
  },
  instance_used_1a : {
    en : "you can't use this model..",
    es : "Error durante el proceso",
    de : "to do de",
    tr : "to do tr",
    fr : "Erreur du process",
  },
  uuid_is_current_1a : {
    en : "your current uuid is already used... ",
    es : "Error durante el proceso",
    de : "to do de",
    tr : "to do tr",
    fr : "Erreur du process",
  },
  instane_created_1a : {
    en : "your current uuid is already used... ",
    es : "Error durante el proceso",
    de : "to do de",
    tr : "to do tr",
    fr : "Erreur du process",
  },
  instane_deleted_1a : {
    en : "your apiviz instance has been deleted... ",
    es : "Error durante el proceso",
    de : "to do de",
    tr : "to do tr",
    fr : "Erreur du process",
  },

  // WELCOME NAV
    welcome_nav : {
      en : "Welcome to the Apiviz dataviz website generator",
      es : "Bienvenido.a al generador Apiviz de sitio de datavisualización",
      de : "to do de",
      tr : "to do tr",
      fr : "Bienvenue sur le générateur de site de datavisualisation Apiviz",
    },
    quick_start : {
      en : "Quick start",
      es : "Empezar ya",
      de : "to do de",
      tr : "to do tr",
      fr : "Commencer",
    },

  // WELCOME
    welcome_1 : {
      en : "Welcome to Apiviz",
      es : "Bienvenido.a en Apiviz",
      de : "to do de",
      tr : "to do tr",
      fr : "Bienvenue sur Apiviz",
    },
    welcome_2 : {
      en : "select a model to create a brand new apiviz website ",
      es : "elegir un módelo para crear un nuevo sitio con Apiviz",
      de : "to do de",
      tr : "to do tr",
      fr : "sélectionnez un modèle pour créer un site original de datavisualisation",
    },

  // INTROS
    intro_1a : {
      en : "Create a new data visualisation website",
      es : "Generar un nuevo sitio de data visualización",
      de : "to do de",
      tr : "to do tr",
      fr : "Créez un nouveau site de datavisualisation",
    },
    intro_1b : {
      en : "in a few clicks with Apiviz !",
      es : "en algunos clics con Apiviz",
      de : "to do de",
      tr : "to do tr",
      fr : "en quelques clics avec Apiviz!",
    },

    intro_2a : {
      en : "To do so you can start with an ",
      es : "Empieze con un",
      de : "to do de",
      tr : "to do tr",
      fr : "Commencez avec un ",
    },
    intro_2b : {
      en : "existing model",
      es : "módelo existante",
      de : "to do de",
      tr : "to do tr",
      fr : "modèle de site",
    },
    intro_2c : {
      en : "and then modify it from the back-office",
      es : "y modificarlo desde el back office",
      de : "to do de",
      tr : "to do tr",
      fr : "que vous pourrez ensuite modifier depuis le back office",
    },
    intro_3a : {
      en : "Apiviz is an",
      es : "Apiviz es un",
      de : "to do de",
      tr : "to do tr",
      fr : "Apiviz est un ",
    },
    intro_3b : {
      en : "so you can also reuse the source code instead of the saas service",
      es : "tambien puedes reutilizar el código en lugar del servicio saas",
      de : "to do de",
      tr : "to do tr",
      fr : "vous pouvez donc réutiliser le code source de l'application au lieu du service en saas ",
    },

  // DIVIDERS
    div_1 : {
      en : "your current UUID",
      es : "su UUID actual",
      de : "to do de",
      tr : "to do tr",
      fr : "votre UUID actuel",
    },
    div_2 : {
      en : "create your datavisualisation website from a model",
      es : "creas su sitio de data visualización a partir de un módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "créez votre site de datavisualisation en partant d'un modèle",
    },
    div_3 : {
      en : "options of the selected model",
      es : "opciones del módelo eligido",
      de : "to do de",
      tr : "to do tr",
      fr : "options du modèle sélectionné",
    },
    div_4 : {
      en : "complementary infos",
      es : "informaciones complementarias",
      de : "to do de",
      tr : "to do tr",
      fr : "informations complémentaires",
    },
    or : {
      en : "OR",
      es : "O SEA",
      de : "to do de",
      tr : "YA DA",
      fr : "OU",
    },

  // SELECT
    select_1a : {
      en : "select a default model ",
      es : "elige un módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "sélectionnez le modèle",
    },
    select_1b : {
      en : "for your new apiviz website",
      es : "para su nuvo sitio Apivviz",
      de : "to do de",
      tr : "to do tr",
      fr : "de votre nouveau site Apiviz",
    },
    select_1c : {
      en : "Please select a model",
      es : "Elige su módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "Sélectionnez votre modèle",
    },

  // ENTER UUIDS
    uuid_1a : {
      en : "you already have ",
      es : "ya tienes",
      de : "to do de",
      tr : "to do tr",
      fr : "vous avez déjà",
    },
    uuid_1b : {
      en : "a model's UUID",
      es : "el UUID del módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "l'UUID du modèle",
    },
    uuid_1c : {
      en : "enter an UUID",
      es : "entre un UUID",
      de : "to do de",
      tr : "to do tr",
      fr : "entrez un UUID",
    },
    uuid_invalid : {
      en : "This model is invalid",
      es : "Este módelo no es valido",
      de : "to do de",
      tr : "to do tr",
      fr : "Ce modèle n'est pas valide",
    },

  // FEEDBACKS
    feedback_1 : {
      en : "your current UUID : ",
      es : "su UUID actual :",
      de : "to do de",
      tr : "to do tr",
      fr : "votre UUID actuel : ",
    },
    feedback_1a : {
      en : "model's name : ",
      es : "el nombre del módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "nom du modèle : ",
    },
    feedback_1b : {
      en : "model's UUID : ",
      es : "UUID del módelo :",
      de : "to do de",
      tr : "to do tr",
      fr : "UUID du modèle : ",
    },
    feedback_preview : {
      en : "preview of the selected model",
      es : "previsualización del módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "prévisualisation du modèle sélectionné",
    },

  // TAGS
    tags_1a : {
      en : "model's options : ",
      es : "opciones del módelo :",
      de : "to do de",
      tr : "to do tr",
      fr : "options du modèle :",
    },
    dynamic_template : {
      en : "route types",
      es : "tipos de rutas",
      de : "to do de",
      tr : "to do tr",
      fr : "types de routes",
    },
    endpoint_type : {
      en : "data endpoint types",
      es : "tipos de puntos de API",
      de : "to do de",
      tr : "to do tr",
      fr : "types de points d'API",
    },

  // SPECS
    app_colors : {
      en : "model's colors ",
      es : "colores del módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "couleurs du modèle",
    },
    app_colors_class : {
      en : "colors class",
      es : "clases del módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "classe couleur",
    },
    app_colors_color : {
      en : "color",
      es : "colores",
      de : "to do de",
      tr : "to do tr",
      fr : "couleur",
    },
    app_colors_code : {
      en : "color code ",
      es : "código color",
      de : "to do de",
      tr : "to do tr",
      fr : "code couleur",
    },
    app_languages : {
      en : "model's languages ",
      es : "idiomas del módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "langues du modèle",
    },

  // TITLE
    title_1a : {
      en : "title of your new website ",
      es : "título de su nuevo sitio",
      de : "to do de",
      tr : "to do tr",
      fr : "titre de votre nouveau site",
    },
    title_1b : {
      en : "the title of your new website ",
      es : "el título de su nuevo sitio",
      de : "to do de",
      tr : "to do tr",
      fr : "le titre de votre nouveau site",
    },

  // LOGO
    logo_1a : {
      en : "Your new website logo ",
      es : "el logo de su nuevo sitio",
      de : "to do de",
      tr : "to do tr",
      fr : "Le logo de votre nouveau site",
    },
    logo_1b : {
      en : "enter your logo url",
      es : "entre el URL de su logo",
      de : "to do de",
      tr : "to do tr",
      fr : "entrez l'url vers l'image de votre logo",
    },
    logo_1c : {
      en : "preview of your logo",
      es : "previsualización de su logo",
      de : "to do de",
      tr : "to do tr",
      fr : "prévisualisation de votre logo",
    },

  // EMAIL
    admin_1a : {
      en : "admin infos ",
      es : "infos admin",
      de : "to do de",
      tr : "to do tr",
      fr : "infos admin",
    },
    name_1a : {
      en : "your name ",
      es : "su nombre",
      de : "to do de",
      tr : "to do tr",
      fr : "votre prénom",
    },
    name_1b : {
      en : "your name as the first admin",
      es : "su nombre de admin",
      de : "to do de",
      tr : "to do tr",
      fr : "votre prénom de premier admin",
    },
    surname_1a : {
      en : "your surname ",
      es : "su apellido",
      de : "to do de",
      tr : "to do tr",
      fr : "votre nom de famille",
    },
    surname_1b : {
      en : "your surname as the first admin",
      es : "su apellido de admin",
      de : "to do de",
      tr : "to do tr",
      fr : "votre nom de famille ",
    },
    email_1a : {
      en : "your email ",
      es : "su email",
      de : "to do de",
      tr : "to do tr",
      fr : "votre email",
    },
    email_1b : {
      en : "the email you will use to log as as the first admin",
      es : "el email que vas a usar para conectarte como admin",
      de : "to do de",
      tr : "to do tr",
      fr : "l'email qui vous servira pour vous connecter en tant que premier admin",
    },
  // DATA
    data_new_endpoint_question : {
      en : "I want to enter a new Solidata endpoint",
      es : "Quiero entrar un nuevo endpoint Solidata para mis datos",
      de : "to do de",
      tr : "to do tr",
      fr : "Je veux préciser un nouvel endpoint Solidata pour mes données",
    },
    data_solidata_endpoint_url_1a : {
      en : "Your dataset ID in Solidata",
      es : "Su dataset ID en Solidata",
      de : "to do de",
      tr : "to do tr",
      fr : "L'ID de votre dataset dans Solidata",
    },
    data_solidata_endpoint_url_1b : {
      en : "Your Solidata dataset's ID",
      es : "Su dataset ID en Solidata",
      de : "to do de",
      tr : "to do tr",
      fr : "L'ID de votre dataset dans Solidata",
    },
    data_solidata_endpoint_url_1c : {
      en : "new Solidata endpoint",
      es : "nuevo endpoint Solidata",
      de : "to do de",
      tr : "to do tr",
      fr : "nouveau endpoint Solidata",
    },
    data_new_endpoint_dsType : {
      en : "dataset type",
      es : "tipo de dataset",
      de : "to do de",
      tr : "to do tr",
      fr : "type de dataset",
    },
    data_new_endpoint_dsId : {
      en : "dataset ID",
      es : "ID del dataset",
      de : "to do de",
      tr : "to do tr",
      fr : "ID du dataset",
    },

  // CREATE
    create_1a : {
      en : "Generate your new website",
      es : "Genere su nuevo sitio",
      de : "to do de",
      tr : "to do tr",
      fr : "Générez votre nouveau site",
    },
    create_1b : {
      en : "Choose a model first",
      es : "Primero elige un módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "Merci de choisir un modèle",
    },
    create_1c : {
      en : "Choose an admin email first",
      es : "Primero elige un email de admin",
      de : "to do de",
      tr : "to do tr",
      fr : "Merci de choisir un email d'admin",
    },
    create_1d : {
      en : "Choose a model and an email admin first",
      es : "Elige un módelo y un email de admin",
      de : "to do de",
      tr : "to do tr",
      fr : "Merci de choisir un modèle et un email d'admin",
    },

  // GO TO
    goto_1a : {
      en : "See your new website",
      es : "Ver su nuevo sitio",
      de : "to do de",
      tr : "to do tr",
      fr : "Accédez à votre nouveau site",
    },

  // OTHERS
    repo: {
      en : "source code on Github",
      es : "código fuente en Github",
      de : "to do de",
      tr : "to do tr",
      fr : "code source sur Github",
    },

    check_repo: {
      en : "Check the repo",
      es : "Ver el repo",
      de : "to do de",
      tr : "to do tr",
      fr : "Code source",
    },
    check_docs: {
      en : "Check the documentation",
      es : "Ver la documentación",
      de : "to do de",
      tr : "to do tr",
      fr : "Voir la documentation",
    },
    open_source_pr: {
      en : "open source project",
      es : "proyecto open source",
      de : "to do de",
      tr : "to do tr",
      fr : "projet open source",
    },

  // STEPPERS
    step_title: {
      en : "your title",
      es : "su título",
      de : "to do de",
      tr : "to do tr",
      fr : "votre titre",
    },
    step_model: {
      en : "your model",
      es : "su módelo",
      de : "to do de",
      tr : "to do tr",
      fr : "votre modèle",
    },
    step_logo: {
      en : "your logo",
      es : "su logo",
      de : "to do de",
      tr : "to do tr",
      fr : "votre logo",
    },
    step_email: {
      en : "admin email",
      es : "email de admin",
      de : "to do de",
      tr : "to do tr",
      fr : "email d'admin",
    },
    step_data: {
      en : "your data",
      es : "sus datos",
      de : "to do de",
      tr : "to do tr",
      fr : "vos données",
    },
    step_finish: {
      en : "generate",
      es : "generar",
      de : "to do de",
      tr : "to do tr",
      fr : "générer",
    },
    docs: {
      en : "documentation",
      es : "documentación",
      de : "to do de",
      tr : "to do tr",
      fr : "documentation",
    },
    next: {
      en : "next",
      es : "siguiente",
      de : "to do de",
      tr : "to do tr",
      fr : "suivant",
    },
    previous: {
      en : "previous",
      es : "previo",
      de : "to do de",
      tr : "to do tr",
      fr : "précédent",
    },

  // FOR BACK OFFICE

    modal_doc_1a : {
      en : 'To know more about the',
      es : "Para saber mas a propocito de los ajustes",
      de : "to do de",
      tr : "to do tr",
      fr : 'Pour en savoir plus sur les réglages de la configuration'
    },
    modal_doc_1b : {
      en : "settings",
      es : "",
      de : "to do de",
      tr : "to do tr",
      fr : ''
    },
    modal_doc_1c : {
      en : 'check our documentation here ',
      es : "ver nuestra documentation",
      de : "to do de",
      tr : "to do tr",
      fr : 'consultez notre documentation ici'
    },
    modal_doc_1d : {
      en : 'apiviz documentation website',
      es : "sitio de deocumentatción de Apiviz",
      de : "to do de",
      tr : "to do tr",
      fr : "site de documentation d'Apiviz",
    },

    bo_delete_confirm_1a : {
      en : 'Are you sure you want to delete this element? ',
      es : "¿Estais seguro.a que queréis suprimir este elemento?",
      de : "to do de",
      tr : "to do tr",
      fr : 'Êtes-vous certain.e de vouloir supprimer ce document?',
    },
    bo_delete_btn : {
      en : 'yes, delete',
      es : "si, suprimir",
      de : "to do de",
      tr : "to do tr",
      fr : 'oui, supprimer',
    },

    bo_helper_1a : {
      en : 'you can do the following (experimental) :',
      es : "podeis hacer lo siguiente (experimental)",
      de : "to do de",
      tr : "to do tr",
      fr : 'vous pouvez faire les opérations suivantes (expérimental) :',
    },
    bo_helper_2a : {
      en : 'delete or duplicate this element ',
      es : "suprimir o duplicar este elemento",
      de : "to do de",
      tr : "to do tr",
      fr : 'supprimer ou dupliquer ce document',
    },
    bo_helper_2a_ : {
      en : "beware to create an original value for the following fields : 'field' (and 'tab_uri') ",
      es : "tenga cuidado crear un valor para los siguientes campos : 'field' (y 'tab_uri') ",
      de : "to do de",
      tr : "to do tr",
      fr : "prenez garde à bien créer une nouvelle valeur pour les champs suivants : 'field' (et 'tab_uri')",
    },
    bo_helper_2b : {
      en : 'modify the values',
      es : "modificarr los valores",
      de : "to do de",
      tr : "to do tr",
      fr : 'modifier les valeurs',
    },
    bo_helper_2c : {
      en : 'add new key(s) at your own risk',
      es : "añadir nuevas llaves (keys) a sus propios riesgos",
      de : "to do de",
      tr : "to do tr",
      fr : 'ajouter de nouvelles entrées (à votre propre rique)',
    },
    bo_helper_2d : {
      en : 'add new entries to the lists (but beware to respect the format)',
      es : "añadir nuevos valores a las listas (pero tennga cuidado respetar al formato)",
      de : "to do de",
      tr : "to do tr",
      fr : 'ajouter une nouvelle entrée aux listes (attention de respecter le format)',
    },
    bo_helper_2e : {
      en : 'modifying the keys will not be taken into account',
      es : "modificar las llaves (keys) no sera tomado en cuenta",
      de : "to do de",
      tr : "to do tr",
      fr : 'modifier les champs clés ne sera pas pris en compte',
    },
    bo_helper_2f : {
      en : 'modify the existing keys (at your own risk)',
      es : "modificar las llaves (keys) existantes",
      de : "to do de",
      tr : "to do tr",
      fr : 'modifier les champs clés existants (à votre propre risque)',
    },

    bo_test : {
      en : 'test',
      es : "probar",
      de : "to do de",
      tr : "to do tr",
      fr : 'tester',
    },
    bo_warning : {
      en : 'warning',
      es : "cuidado",
      de : "to do de",
      tr : "to do tr",
      fr : 'attention',
    },
    bo_delete : {
      en : 'delete',
      es : "suprimir",
      de : "to do de",
      tr : "to do tr",
      fr : 'supprimer',
    },
    bo_save : {
      en : 'save',
      es : "guardar",
      de : "to do de",
      tr : "to do tr",
      fr : 'enregistrer',
    },
    bo_cancel : {
      en : 'cancel',
      es : "anular",
      de : "to do de",
      tr : "to do tr",
      fr : 'annuler',
    },
    bo_add : {
      en : 'add a document ',
      es : "añadir un documento",
      de : "to do de",
      tr : "to do tr",
      fr : 'ajouter un document ',
    },

    // duplicate
    bo_duplicate_title : {
      en : 'Duplicate a document ',
      es : "Duplicar un documento",
      de : "to do de",
      tr : "to do tr",
      fr : 'Dupliquer un document',
    },
    bo_duplicate_intro_1a : {
      en : 'You can add a new document to this collection',
      es : "Podeis añadir un nuevo documento a la colección",
      de : "to do de",
      tr : "to do tr",
      fr : 'Vous pouvez ajouter un document à cette collection',
    },
    bo_duplicate_intro_1b : {
      en : 'by duplicating an existing one',
      es : "duplicando un documento existante",
      de : "to do de",
      tr : "to do tr",
      fr : 'en dupliquant un document existant',
    },
    bo_duplicate_select_helper : {
      en : 'Select the document you want to duplicate',
      es : "Elegir un documento que quiereis duplicar",
      de : "to do de",
      tr : "to do tr",
      fr : 'Sélectionner le document que vous souhaitez dupliquer',
    },
    bo_duplicate_edit_helper : {
      en : 'You can edit the selected document before sending it',
      es : "Podeis editar el documento elegido antes mandarlo",
      de : "to do de",
      tr : "to do tr",
      fr : "Vous pouvez éditer le document avant de l'envoyer",
    },
    bo_duplicate_select_placeholder : {
      en : 'Select a document ',
      es : "Elegir un documento",
      de : "to do de",
      tr : "to do tr",
      fr : 'Sélectionner un document',
    },

    bo_title : {
      en : 'Back office',
      es : "Espacio de configuración",
      de : "to do de",
      tr : "to do tr",
      fr : 'Espace de configuration',
    },
    bo_back : {
      en : 'Back to previous page',
      es : "Volver a la página anterior",
      de : "to do de",
      tr : "to do tr",
      fr : 'Retour à la page précédente',
    },





// GLOBALLY BASICS
  login : {
    en : "Login",
    es : "Login",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Login",
  },
  connect : {
    en : "Connect",
    es : "Conectarse",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Se connecter",
  },
  connected      : {
    en : "already connected",
    es : "ya conectado.a",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "déjà connecté.e",
  },
  reconnect      : {
    en : "Reconnect",
    es : "Reconectarse",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Se reconnecter",
  },
  disconnect     : {
    en : "Disconnect",
    es : "Desconectarse",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Se déconnecter",
  },
  disconnect_msg : {
    en : "you successfully disconnected",
    es : "se disconectó con exito",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Vous avez été déconnecté.e avec succès",
  },
  want_disconnect: {
    en : "Do you want to disconnect?",
    es : "¿Queréis desconectarse?",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Voulez-vous vous déconnecter?",
  },
  want_reconnect: {
    en : "Do you want to reconnect?",
    es : "¿Queréis reconectarse?",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Voulez-vous vous reconnecter?",
  },
  is_account     : {
    en : "You already have an account?",
    es : "¿Ya tenéis una cuenta?",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Vous avez déjà un compte?",
  },
  no_account     : {
    en : "You don't have an account yet?",
    es : "¿Todavía no tenéis cuenta?",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Vous n'avez pas encore de compte?",
  },
  register : {
    en : "Register",
    es : "Registrarse",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "S'inscrire",
  },
  optionnal : {
    en : "optionnal",
    es : "opcional",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "optionnel",
  },
  preferences : {
    en : "Preferences",
    es : "Preferencias",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Préférences",
  },
  backoffice : {
    en : "Back office",
    es : "Back office",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Back office",
  },
  is_registered  : {
    en : "You are already registred",
    es : "Ya estais registrado.a",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Vous êtes déjà inscrit.e",
  },
  logout  : {
    en : "Logout",
    es : "Salir",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Se déconnecter",
  },
  hello : {
    en : "hello",
    es : "hola",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "bonjour",
  },
  email : {
    en : "email",
    es : "email",
    tr : "email",
    de : "email",
    fr : "email",
  },
  name  : {
    en : "name",
    es : "nombre",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "prénom",
  },
  surname  : {
    en : "surname",
    es : "apellido",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "nom",
  },
  password : {
    en : "password",
    es : "contraseña",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "mot de passe",
  },
  password_confirm : {
    en : "confirm the password",
    es : "confirma su contraseña",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "confirmer le mot de passe",
  },
  password_bis   : {
    en : "repeat the password",
    es : "repite su contraseña",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "répéter le mot de passe",
  },
  remember_me    : {
    en : "remember me",
    es : "acordarse de mi",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "se souvenir de moi",
  },
  forgot_password: {
    en : "Forgot your password?",
    es : "¿Contraseña olvidada?",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Mot de passe oublié?",
  },
  create_account : {
    en : "Create an account",
    es : "Crea una cuenta",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Créer un compte",
  },
  accept_cgu     : {
    en : "Accept CGU",
    es : "Accepto los CGU",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "J'accepte les CGU",
  },

  // ### for back office
  menu_app_settings   : {
    en : "CONFIGURATION",
    es : "CONFIGURACION",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "CONFIGURATION",
  },
  menu_preferences    : {
    en : "PREFERENCES",
    es : "PREFERRENCIAS",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "PREFERENCES",
  },

  // # menus
  bo_global : {
    en : "global",
    es : "global",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "global",
  },
  bo_navbar : {
    en : "navigation",
    es : "navegación",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "navigation",
  },
  bo_routes : {
    en : "routes",
    es : "rutas",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "routes",
  },
  bo_endpoints : {
    en : "data",
    es : "data",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "données",
  },
  bo_tabs   : {
    en : "tabs",
    es : "tabs",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "tabs",
  },
  bo_footer : {
    en : "footer",
    es : "footer",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "footer",
  },
  bo_socials  : {
    en : "socials",
    es : "sociales",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "réseaux sociaux",
  },
  bo_styles : {
    en : "styles",
    es : "estilos",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "styles",
  },
  bo_users  : {
    en : "users",
    es : "usuarios",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "utilisateurs",
  },

  // # tabs
  gl_general : {
    en : "general",
    es : "general",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "général",
  },
  gl_identity  : {
    en : "identity",
    es : "identidad",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "identité du site",
  },
  gl_meta    : {
    en : "meta",
    es : "meta",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "meta",
  },
  gl_seo     : {
    en : "SEO",
    es : "SEO",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "SEO",
  },
  gl_lang    : {
    en : "international",
    es : "internacional",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "international",
  },
  na_global  : {
    en : "navbar",
    es : "navbar",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "navbar",
  },
  na_links   : {
    en : "navbar links",
    es : "vínculos navbar",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "liens navbar",
  },
  ro_data    : {
    en : "data routes",
    es : "rutas data",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "routes data",
  },
  ro_statics : {
    en : "pages routes",
    es : "rutas páginas",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "routes pages",
  },
  ro_user    : {
    en : "user routes",
    es : "rutas usuarios",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "routes utilisateur",
  },
  ep_data_filters     : {
    en : "filters",
    es : "fieltros",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "filtres",
  },
  ep_data    : {
    en : "data",
    es : "data",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "données",
  },
  ep_auth    : {
    en : "authentication",
    es : "autentificación",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "authentification",
  },
  ep_user    : {
    en : "users",
    es : "usuarios",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "utilisateurs",
  },
  ta_tabs    : {
    en : "tabs",
    es : "tabs",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "tabs",
  },
  fo_settings  : {
    en : "footer",
    es : "footer",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "footer",
  },
  fo_links   : {
    en : "footer links",
    es : "vínculos footer",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "liens footer",
  },
  so_settings  : {
    en : "socials",
    es : "redes socials",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "réseaux sociaux",
  },
  st_colors  : {
    en : "colors",
    es : "colores",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "couleurs",
  },
  st_typo    : {
    en : "typos",
    es : "tipografías",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "typos",
  },
  st_typocolors : {
    en : "typo colors",
    es : "typo colores",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "couleurs typo",
  },
  st_banners : {
    en : "banners",
    es : "banderas",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "bannières",
  },
  st_images  : {
    en : "images",
    es : "imagenes",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "images",
  },
  us_users   : {
    en : "users list",
    es : "lista usuarios",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "liste utilisateurs",
  },
  us_teams   : {
    en : "teams list",
    es : "lista equipos",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "liste équipes",
  },

  // # preferences
  u_infos    : {
    en : "infos",
    es : "infos",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "infos",
  },
  u_password : {
    en : "security",
    es : "securidad",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "sécurité",
  },
  u_logout   : {
    en : "logout",
    es : "logout",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "logout",
  },
  u_contact  : {
    en : "contact",
    es : "contacto",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "contact",
  },
  u_profile  : {
    en : "profile",
    es : "perfil",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "profil",
  },
  u_about    : {
    en : "message",
    es : "mensaje",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "message",
  },
  u_about_more : {
    en : "How can we help?",
    es : "¿Como podriamos ayudarle?",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "Comment pourrions-nous vous aider?",
  },
  u_infos_send : {
    en : "update my infos",
    es : "actualizar sus infos",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "mettre à jour les informations",
  },
  password_new : {
    en : "your new password",
    es : "su neuva contraseña",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "votre nouveau mot de passe",
  },
  password_send : {
    en : "update my password",
    es : "actualizar mi contraseña",
    tr : "yapılmamış",
    de : "ungemacht",
    fr : "enregister le nouveau mot de passe",
  },





}
